version: '3.8'

services:
  db:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nutrition_app
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    build: .
    environment:
      DB_HOST: 88.99.227.238
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: nutrition_app
      DB_PORT: 5432
    ports:
      - "1010:1010"
    depends_on:
      - db

volumes:
  postgres_data:
